micronaut:
  application:
    name: sparkled
    
  io:
    watch:
      paths:
        - src/main
        - model/src/main
        - music-player/src/main
        - persistence/src/main
        - renderer/src/main
        - rest/src/main
        - scheduler/src/main
        - udp-server/src/main
      restart: true

  router:
    static-resources:
      default:
        paths:
          - classpath:webui

  server:
    maxFileSize: 30mb
    maxRequestSize: 30mb
    multipart:
      maxFileSize: 30mb
    cors:
      enabled: true

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:./sparkled`}
    username: ${JDBC_USER:}
    password: ${JDBC_PASSWORD:}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

jackson:
  serializationInclusion: ALWAYS # Include empty arrays in JSON output
  deserialization:
    failOnUnknownProperties: false # Enables backward compatibility for effect JSON containing removed fields.
    readUnknownEnumValuesUsingDefaultValue: true # Backward compatibility for effect JSON containing removed enums.

jpa:
  default:
    packages-to-scan:
      - 'io.sparkled.model.entity'

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'

sparkled:
  directory: './data'
